spring:
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: application
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: '0'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:1111/eureka'
    instance:
      leaseRenewalIntervalInSeconds: 1000;
      leaseExpriationDurationInSeconds: '2000'
  instance:
    hostname: localhost
    instance-id: >-
      ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
ribbonService:
  ribbon:
    DeploymentContextBasedVipAddresses: finesService
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    eureka:
      enabled: true
management:
  endpoints:
    info:
      enabled: true
    web:
      exposure:
        include: 'health,info'
  info:
    env:
      enabled: true
info:
  app:
    build:
      name: '@project.name@'
