spring:
  application:
    name: eureka_server

server:
  port: 1111

#eureka.client.registerWithEurka controls whether the client registers itself ( becomes discoverable)
#   Don't let the server register itself
# eureka.client.fetchRegistery controls whether the client is going to try to connect to the server to 
#   download data on other services endpoint and caches it locally -- This is a server
eureka:
  instance:
    hostname: localhost
  client:  
    registerWithEureka: false
    fetchRegistry: false
