version: '4'
services:
  mongodb:
    image: mongo:7.0.5            # Could also be latest
    container_name: mongodb
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASEP: product-service
    volumes:
      # Stores the data or else all data will be lost.
      # In the tutorial they could have a relative path, but
      - ./data:/data/db